# version: "3.8"
# name: my-eclipse-mosquitto-project - cannot use like this, use -p to chane name of stack
services:
  mymosquitto:
    image: registry.hub.docker.com/library/eclipse-mosquitto
    volumes:
      - eclipse-mosquitto-mydata:/mosquitto
    ports:
      - 9001:9001
      - 1883:1883
    domainname: "my-mq-project"

volumes:
  eclipse-mosquitto-mydata:
    driver: azure_file
    driver_opts:
      share_name: test-mosquitto
      storage_account_name: testmstachyra